// examples/h3-v2/src/app.tsx
import { lazy } from 'solid-js'
import { type AppProps, Route, Router } from 'solid-rouage/client'
import { Layout } from './components/layout'

export const App = (props: AppProps) => (
  <Router path={props.path} root={(props) => <Layout>{props.children}</Layout>}>
    <Route path="/" component={lazy(() => import('./components/home'))} />
    <Route path="/about" component={lazy(() => import('./components/about'))} />
  </Router>
)

// examples/env/src/app.tsx
import { Link, MetaProvider } from '@solidjs/meta'
import { Route, Router } from '@solidjs/router'
import styles from './app.css?url'

import { About } from './components/about'
import { Home } from './components/home'

export const App = (props: { path?: string }) => (
  <Router
    url={props.path}
    root={(props) => (
      <MetaProvider>
        <Link rel="stylesheet" href={styles} />
        {props.children}
      </MetaProvider>
    )}
  >
    <Route path="/" component={Home} />
    <Route path="/about" component={About} />
  </Router>
)
