// examples/env/src/app.tsx
import { Link, MetaProvider } from '@solidjs/meta'
import { Route, Router } from '@solidjs/router'
import styles from './app.css?url'

import { About } from './components/about'
import { Home } from './components/home'

export const App = (props: { path?: string }) => (
  <Router
    url={props.path}
    root={(props) => (
      <MetaProvider>
        <Link rel="stylesheet" href={styles} />
        {props.children}
      </MetaProvider>
    )}
  >
    <Route path="/" component={Home} />
    <Route path="/about" component={About} />
  </Router>
)

// examples/demo/src/app.tsx
import { MetaLink, MetaProvider, Route, Router } from '@granite/core'
import { Suspense, lazy } from 'solid-js'
import styles from './app.css?url'

const Home = lazy(() => import('./components/home').then((module) => ({ default: module.Home })))
const About = lazy(() => import('./components/about').then((module) => ({ default: module.About })))

export const App = (props: { path?: string }) => (
  <Router
    url={props.path}
    root={(props) => (
      <MetaProvider>
        <MetaLink rel="stylesheet" href={styles} />
        <Suspense>{props.children}</Suspense>
      </MetaProvider>
    )}
  >
    <Route path="/" component={Home} />
    <Route path="/about" component={About} />
  </Router>
)
